### ISSUE TITLE
Sendding  parameters to mapper

### ISSUE THREAD

**Issue by Shailuc** [mvallebr/CSVInputFormat#11]
Hi,

```
I am new to Big Data and Mao reduce ,   I want to send the columnIndex to print the particular column value in the row, where can I set this additional parameter to mapper. Please respond
```

**Comment by mvallebr** [comment]
You can add this to the hadoop context, it will be available to all nodes during map phase. It should be very simple to do

I am sorry I have been having little time to contribute more to this project, if you want to submit pull requests I will gladly analyse them

**Comment by Shailuc** [comment]
Hey Thanks mvallebr , I passed the parameters to configuration, It worked . I am actually working on reading two different csv files related by a common  column name, I dont think I can do it in sigle mapper (passing splits for two different files in single mapper). Please provide some inputs.

**Comment by mvallebr** [comment]
It's not currently implemented, but can be done. There are some ways of doing it, it would be possible to add configuration options to the input format for that, allowing you to specify a map of file name -> column set . It would be set like in here: https://github.com/mvallebr/CSVInputFormat/blob/master/src/test/java/org/apache/hadoop/mapreduce/lib/input/CSVNLineInputFormatTest.java#L76

There are probably more ways I would have to check in more details later... Are you using a streaming process? Maybe the best option to you would be adding streaming tasks and for each task specify a cfg filename... 

Other option - you could use the same file name with `.cfg` extension for the column set configuration and put also on HDFS, so all nodes would also be able to read it...
