### ISSUE TITLE
LICENSE about this library

### ISSUE THREAD

**Issue by tsukaby** [mvallebr/CSVInputFormat#14]
@mvallebr 

Hi mvallebr
Could you tell me the license for this library? 
Thank you!

**Comment by mvallebr** [comment]
It's Apache 2.0

https://github.com/mvallebr/CSVInputFormat/blob/eea963ba516439eb00c9eb73c7dcb1bf23ddbbcd/src/main/java/org/apache/hadoop/mapreduce/lib/input/ArrayListTextWritable.java

I will add later a file in the same level as readme to make it more clear

**Comment by mvallebr** [comment]
added LICENSE.md, please reopen this issue if you need anything else

**Comment by tsukaby** [comment]
Thank you!
