### ISSUE TITLE
Question about records spanning splits

### ISSUE THREAD

**Issue by atrigent** [mvallebr/CSVInputFormat#16]
Hello! I've been looking through the code for this project, and I do see how `CSVLineRecordReader` reads multiple lines if necessary, but I'm having trouble seeing how you handle the case where a record lies across a split boundary. The line reader stuff in Hadoop itself seems to have some handling where it will read a little beyond the end point that it is told in order to read a full line, and will skip the first line at the start point that it is told so as not to double-read the line that was read as part of the previous split. I don't see anything like that in this project. Am I missing something? If so, could you point me to how that is handled/implemented?

Thanks!

**Comment by mvallebr** [comment]
Hi, this was asked long time ago, but I think it's better to answer now than leaving it without an answer. Sorry for my lack of priority to this project. 

The lines are read twice indeed - first, the whole file is read on a single machine and splits are generated from this file. Then the record reader is used again to read lines from the splits in all machines. 

The advantage here is that in the machine where the big file is split, as long as it fits the disk space available, no memory is used to split it - the output are just the coordinates of beginning of the first line in the split, end of the last line of the split.

Hope it makes sense.
