### ISSUE TITLE
org.apache.hadoop.mapreduce.TaskAttemptContext is abstract; cannot be instantiated

### ISSUE THREAD

**Issue by colmac3** [mvallebr/CSVInputFormat#4]
This is my error:
compile:
    [javac] /Users/colmac/Java/CSVInputFormat-master/build.xml:20: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 8 source files to /Users/colmac/Java/CSVInputFormat-master/build
    [javac] /Users/colmac/Java/CSVInputFormat-master/src/test/java/org/apache/hadoop/mapreduce/lib/input/CSVNLineInputFormatTest.java:23: org.apache.hadoop.mapreduce.TaskAttemptContext is abstract; cannot be instantiated
    [javac]         TaskAttemptContext context = new TaskAttemptContext(conf, new TaskAttemptID());
    [javac]                                      ^
    [javac] /Users/colmac/Java/CSVInputFormat-master/src/test/java/org/apache/hadoop/mapreduce/lib/input/CSVNLineInputFormatTest.java:26: org.apache.hadoop.mapreduce.JobContext is abstract; cannot be instantiated
    [javac]         List<InputSplit> actualSplits = inputFormat.getSplits(new JobContext(conf, new JobID()));
    [javac]                                                               ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors

I did a bit of searching and found this:
it has become an interface in Hadoop 2.x so the code needs to be reworked

Is this something you can fix?

**Comment by psuryawanshi** [comment]
Hey @mvallebr Do you get chance to recompile them to make compatible with Hadoop 2 getting similar issue - Please let me know if you can fix it -

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project CSVInputFormat: Compilation failure: Compilation failure:
[ERROR] /Users/psuryawanshi/CodeBase_Destination/CSVInputFormat/src/test/java/org/apache/hadoop/mapreduce/lib/input/CSVNLineInputFormatTest.java:[38,38] org.apache.hadoop.mapreduce.TaskAttemptContext is abstract; cannot be instantiated
[ERROR] /Users/psuryawanshi/CodeBase_Destination/CSVInputFormat/src/test/java/org/apache/hadoop/mapreduce/lib/input/CSVNLineInputFormatTest.java:[41,63] org.apache.hadoop.mapreduce.JobContext is abstract; cannot be instantiated

changes to pom - 

  <dependency>
                        <groupId>org.apache.hadoop</groupId>
                        <artifactId>hadoop-common</artifactId>
                        <version>2.7.1.2.3.4.0-3485</version>
                </dependency>
   <dependency>
                        <groupId>org.apache.hadoop</groupId>
                        <artifactId>hadoop-mapreduce-client-core</artifactId>
                        <version>2.7.1.2.3.4.0-3485</version>
                </dependency>
