### ISSUE TITLE
Bug in CSVNLineInputFormat.getSplitsForFile?

### ISSUE THREAD

**Issue by ctan** [mvallebr/CSVInputFormat#8]
Line 125 and Line 127 are the same so I was wondering why there's an if-else?
<img width="918" alt="screen shot 2015-08-12 at 7 32 45 am" src="https://cloud.githubusercontent.com/assets/630820/9213383/5cffa4cc-40c4-11e5-840c-ea65f7ff6523.png">

**Comment by mvallebr** [comment]
Hi @ctan, thanks for the contribution. It was doing different things, but after a pull request someone changed the first line and I forgot to see it. 
I will try to test this later, fell free to submit a fix if you want
